### ISSUE TITLE
Error: Cannot find module 'gulp-postcss'

### ISSUE THREAD

**Issue by damianoferrari** [michaeldeboeve/generator-robonkey#4]
I generated a new project that included Rucksack. 'gulp serve' failed with this error:

Error: Cannot find module 'gulp-postcss'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (D:\dev\damiano\gulp\gulp-tasks\styles.js:13:15)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at requireDir (D:\dev\damiano\gulp\node_modules\require-dir\index.js:116:33)
    at Object.<anonymous> (D:\dev\damiano\gulp\gulpfile.js:10:1)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)

I believe PostCSS is required by Rucksack.

**Comment by michaeldeboeve** [comment]
hmm strange, because gulp-postcss should be installed automatically as I use the postcss autoprefixer plugin by default. Is gulp-postcss in your node_modules folder?

**Comment by damianoferrari** [comment]
Let me try with the most recent code.

**Comment by damianoferrari** [comment]
I guess that I didn't have gulp-postcss in node_modules. I installed it globally and now Rucksack is included without any problems. Thanks for the tip!

**Comment by michaeldeboeve** [comment]
Hmm, that's not how it supposed to work, it should be included in the node_modules folder of the project.
Can you provide me the config.json, package.json and .yo-rc.json? Or just tell me what exact options you used, so I can recreate the issue?

**Comment by damianoferrari** [comment]
I removed gulp-postcss from the modules installed globally, then generated a new project with the most recent version of your generator. I used all the default values, except for the CSS post-processors, where I added Rucksack. This time, everything worked fine. Since I can't replicate the issue, we can close this ticket?

**Comment by michaeldeboeve** [comment]
yes, thanks!
